#!/usr/bin/env bash

set -eu
set -o pipefail

readonly SELF=$(basename "${BASH_SOURCE[0]}")
readonly OS=$(uname)
readonly VERSION=0.0.4

OPT_HELP=
OPT_DEBUG=
OPT_VERBOSE=

OPT_BASE_NAME="mvp"

OPT_ELECTRON=git@github.com:themimixcompany/mvp-electron.git
OPT_VIEWER=git@github.com:themimixcompany/mpv-shell.git
OPT_ENGINE=git@github.com:themimixcompany/engine.git

OPT_ARCHS="linux,win32"
OPT_BUILD_DIR=
OPT_SOURCES=
OPT_RELEASES=
OPT_TOKEN=

function error () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "error: ${@}" >&2
  else
    echo -e "\e[0;31m\e[1merror: \e[0;0m${@}" >&2
  fi

  exit 1
}

function warn () {
  if [[ "${OS}" == "Darwin" ]]; then
    echo "warning: ${@}" >&2
  else
    echo -e "\e[0;33mwarning: \e[0;0m${@}" >&2
  fi
}

function debug () {
  if [[ -n "${OPT_DEBUG}" ]]; then
    echo '**'
    echo \${@}: ${@}
    echo \$OPT_HELP: "${OPT_HELP}"
    echo \$OPT_DEBUG: "${OPT_DEBUG}"
    echo \$OPT_VERBOSE: "${OPT_VERBOSE}"
  fi
}

function parseArguments () {
  debug parseArguments "$@"

  local opts=$(getopt -n "${SELF}" --options hdva:b:s:r:t: --longoptions help,debug,verbose,archs:,build-dir:,sources:,releases:,token: -- "$@")

  if [[ $? != 0 ]]; then
    error "Failed to parse arguments. Exiting."
  fi

  eval set -- "${opts}"

  while true; do
    case "$1" in
      (-h|--help) OPT_HELP=true; shift ;;
      (-d|--debug) OPT_DEBUG=true; shift ;;
      (-v|--verbose) OPT_VERBOSE=true; shift ;;
      (-a|--archs) OPT_ARCHS=$2; shift 2 ;;
      (-b|--build-dir) OPT_BUILD_DIR=$2; shift 2 ;;
      (-s|--sources) OPT_SOURCES=$2; shift 2 ;;
      (-r|--releases) OPT_RELEASES=$2; shift 2 ;;
      (-t|--token) OPT_TOKEN=$2; shift 2 ;;
      (--) shift; break ;;
      (*) break ;;
    esac
  done
}

function processArguments () {
  debug processArguments "$@"

  if [[ -n "${OPT_HELP}" || "${#}" -lt 1 ]]; then
    displayUsage
  elif [[ -z "${OPT_ARCHS}" || -z "${OPT_BUILD_DIR}" || -z "${OPT_SOURCES}" || -z "${OPT_RELEASES}" ]]; then
    displayUsage
  else
    return 0
  fi
}

function displayUsage () {
  debug displayUsage "$@"

  cat << EOF
${SELF} [OPTIONS]... <COMMAND> [OPTIONS]...

OPTIONS:
  -h, --help       Show this help

COMMANDS:
  -a, --archs      Comma-separated list of target architectures (default: ${OPT_ARCHS})
  -b, --build-dir  Location for internal building (default: ${OPT_BUILD_DIR})
  -s, --sources    Location where to get the dependencies (default: ${OPT_SOURCES})
  -r, --releases   Location where to create the releases (default: ${OPT_RELEASES})
  -t, --token      The GitHub authentication token
EOF
  exit 0
}

function ensureDirectories () {
  debug ensureDirectories "$@"

  mkdir -p "$OPT_BUILD_DIR"
}

function fetchRemoteElectronSources () {
  debug fetchRemoteElectronSources "$@"

  /opt/bin/ssh-run "git clone $OPT_ELECTRON $OPT_BUILD_DIR/mvp-electron"
}

function fetchRemoteViewerSources () {
  debug fetchRemoteViewerSources "$@"

  /opt/bin/ssh-run "git clone $OPT_VIEWER $OPT_BUILD_DIR/mvp-electron/app/viewer"
}

function fetchRemoteEngineSources () {
  debug fetchRemoteEngineSources "$@"

  /opt/bin/ssh-run "git clone $OPT_ENGINE /root/common-lisp/engine"
}

function buildEngine () {
  debug buildEngine "$@"

  sbcl --eval '(ql:quickload :engine)' \
       --eval '(engine:build #P"/var/lib/build/mvp-electron/app/engine/")'
}

function fetchLocalSources () {
  debug fetchLocalSources "$@"

  git clone ${OPT_SOURCES}/mvp-electron ${OPT_BUILD_DIR}/mvp-electron
  git clone ${OPT_SOURCES}/mvp-shell ${OPT_BUILD_DIR}/mvp-electron/app/viewer
}

function fetchRemoteEngineBinaries () {
  debug fetchRemoteEngineBinaries "$@"

  local dir=${OPT_BUILD_DIR}/mvp-electron/app/engine
  local repo=themimixcompany/engine
  local ver=latest

  local OIFS=${IFS}

  # Note: save the binary to the correct location as conditionalized by OPT_ARCH(S)
  # Note: should the engine must be saved after the creation of a release?

  mkdir -p ${dir}
  cd ${dir}


  if [[ -n "${OPT_ARCHS}" ]]; then
    IFS="," read -ra ARCHITECTURES <<< "${OPT_ARCHS}"
    for a in ${ARCHITECTURES[@]}; do
      case ${a} in
        linux) TOKEN=${OPT_TOKEN} /opt/bin/fetch ${repo} engine_unix_X64 ${ver} ;;
        win32) TOKEN=${OPT_TOKEN} /opt/bin/fetch ${repo} engine_windows_X64.exe ${ver} ;;
        *) warn "fetchRemoteEngineBinaries: No matching engines found. Skipping."; return 0 ;;
      esac
    done
  else
    warn "fetchRemoteEngineBinaries: No archs specified. Skipping."
  fi

  IFS=${OIFS}
}

function fetchDependencies () {
  debug fetchDependencies "$@"

  if [[ "${OPT_SOURCES}" == "github" ]]; then
    #fetchRemoteElectronSources
    #fetchRemoteViewerSources
    #fetchRemoteEngineSources

    #buildEngine
    #fetchRemoteEngineBinaries

    return 0
  else
    fetchLocalSources
    fetchRemoteEngineBinaries
  fi
}

function buildBinaries () {
  debug buildBinaries "$@"
  local OIFS=${IFS}

  cd $OPT_BUILD_DIR/mvp-electron

  # Note: Is this step still necessary?
  npm install

  if [[ -n "${OPT_ARCHS}" ]]; then
    IFS="," read -ra ARCHITECTURES <<< "${OPT_ARCHS}"
    for a in ${ARCHITECTURES[@]}; do
      electron-forge package --platform=${a}
    done
  else
    warn "No archs specified. Skipping."
  fi

  IFS=${OIFS}
}

function createArchReleases () {
  debug createArchReleases "$@"

  local OIFS=${IFS}
  local outSource=${OPT_BUILD_DIR}/mvp-electron/out

  if [[ -n "${OPT_ARCHS}" ]]; then
    IFS="," read -ra ARCHITECTURES <<< "${OPT_ARCHS}"
    for a in ${ARCHITECTURES[@]}; do
      if [[ -d ${outSource}/${OPT_BASE_NAME}-${a}-x64 ]]; then
        cp -av ${outSource}/${OPT_BASE_NAME}-${a}-x64 ${OPT_RELEASES}/${a}
      else
        warn "Release directory not found."
      fi
    done
  else
    warn "No archs specified. Skipping."
  fi

  IFS=${OIFS}
}

function createElectronReleases () {
  debug createElectronReleases "$@"

  rsync -v --exclude out ${OPT_BUILD_DIR}/mvp-electron ${OPT_RELEASES}/electron
}

function createDockerReleases () {
  debug createDockerReleases "$@"

  return 0
}

function createReleases () {
  debug createReleases "$@"

  createArchReleases
  createElectronReleases
  createDockerReleases    # Note: Is it possible to do inside a Docker container?
}

function main () {
  debug main "$@"

  parseArguments "$@"
  processArguments "$@"

  ensureDirectories
  fetchDependencies
  buildBinaries
  createReleases
}

main "$@"
